#ifndef CHTL_COMMON_VERSION_H
#define CHTL_COMMON_VERSION_H

#define CHTL_VERSION_MAJOR 1
#define CHTL_VERSION_MINOR 0
#define CHTL_VERSION_PATCH 0
#define CHTL_VERSION_STRING "1.0.0"

#endif // CHTL_COMMON_VERSION_H